### ISSUE TITLE
Spark version - sorting in spreadsheet view shows now result

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/web-api#10]
e.g., project home  sensisng 2nd try, go to readings, sort on den increasing:

https://demo.vizier.app/vizier-dbprojects/93f092bd19f348ab8210cb8dbf5f11f1?branch=master&version=4

![untitled 2](https://user-images.githubusercontent.com/2989731/44859496-e29f3c80-ac39-11e8-9294-a090e985f002.jpeg)

**Comment by lordpretzel** [comment]
after removing the sorts from the notebook the data is shown again:

https://demo.vizier.app/vizier-dbprojects/93f092bd19f348ab8210cb8dbf5f11f1?branch=master&version=6

**Comment by mrb24** [comment]
fixed by commit: 02e000079c86b82c36c68cfd151654189b37db54
