### ISSUE TITLE
Spark version - Retrieving annotations for cell (based on lens) - NetworkError

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/web-api#12]
https://demo.vizier.app/vizier-dbprojects/3da8a54dd9ac4902afaec655f45e8df8?branch=master&version=9

repeat: click on one of the annotated cells

![untitled](https://user-images.githubusercontent.com/2989731/44860355-9f45cd80-ac3b-11e8-8164-085401f71842.jpeg)

**Comment by mrb24** [comment]
closed by commit: 386cfb133b9d5290d3825d1537e8723a4efe33fb
