### ISSUE TITLE
Error with running missing value lenses

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/web-api#8]
in project `First2` on the demo deployment

~~~
MISSING VALUES FOR 'Grade level' IN 'registrations and testers'

Py4JJavaError:(u'An error occurred while calling t.createLens.\n', JavaObject id=o16)
~~~

**Comment by okennedy** [comment]
@mrb24 could you have a quick look at this?

**Comment by mrb24** [comment]
This issue is fixed on the spark backed demo: https://demo.vizier.app/vizier-db 
I will get the fix into the other demo early next week.

**Comment by lordpretzel** [comment]
great. A potential pitfall for new users I found is that the meaning of constraint may not be clear and if something that is not a valid constraint is entered the same error appears on both version (that is not per se a bug, more a place where to show a more helpful error message).
