### ISSUE TITLE
Spark version - NetworkError when loading datasets in some projects

### ISSUE THREAD

**Issue by lordpretzel** [VizierDB/web-api#9]
e.g., in project Home Sensing.
![untitled](https://user-images.githubusercontent.com/2989731/44858855-8ee02380-ac38-11e8-8ea5-b34ad48e8c8b.jpeg)

**Comment by lordpretzel** [comment]
haven't encountered it when loading a dataset myself.

**Comment by mrb24** [comment]
Fixed.
